#!/usr/bin/env bash

#SBATCH --job-name=ams530_project4
#SBATCH --output=project4.log
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=10
#SBATCH --time=04:00:00
#SBATCH -p short-28core

# load an MPI module
module load mvapich2/gcc12.1/2.3.7

# set env variables which may help performance

export MV2_HOMOGENEOUS_CLUSTER=1
export MV2_ENABLE_AFFINITY=0

# compile the code with the mpi compiler wrapper
mpicc ./project4.c -o mpi_project4

# execute the code with MPI
mpirun ./mpi_project4 > output.out
